FEAT | location section
CE-SMART-CAREER/ce-smart-career-2024 pull request #18
Opened 2024-10-23 19:39 UTC by Peqchji

2024-10-24 10:59 UTC, Kittonn requested changes

2024-10-24 10:59 UTC, Kittonn commented on public/assets/icons/search-icon.svg
ใช้ iconify ดีไหม

2024-10-24 13:58 UTC, Peqchji commented on public/assets/icons/search-icon.svg
ก็ดี

2024-10-26 13:34 UTC, Kittonn commented on src/modules/home/_sections/location.tsx
> +                  placeholder="พิมพ์ชื่อบริษัทย์"
บริษัท ?

2024-10-26 13:35 UTC, Kittonn commented on src/modules/home/_sections/location.tsx
> +
// ====================================================== แบบ P zan

2024-10-26 13:38 UTC, merged